### ISSUE TITLE
Main organization

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#1]
The goal of this project is that given and ontology, you can create an API for it with insertion, update and delete capabilities. This entails the following operations
- [x] Given an ontology, create an API skeleton
- [x] Given an ontology, creates shapes and queries for validation and querying
- [ ] Set up https://github.com/dgarijo/sparql-jsonld to return JSON in the appropriate format
- [x] Set up Open API automatically with its calls.
- [ ] Set up GRLC to be able to customize queries, or set up an alternative for allowing custom queries.
- [ ] Integration of everything in a single application

**Comment by sirspock** [comment]
Invalid
