### ISSUE TITLE
Need to easily incorporate GRLC queries into an API

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#17]
At the moment the queries defined externally to the original API are not straightforward to incorporate. You have to move them into a folder, then add a line into a script for them to be added, etc. 

Ideally, I would like the system to have the ability to read GET queries from an external GitHub repository as GRLC does. Since we are extending GRLC, it should be doable.

**Comment by sirspock** [comment]
OBA does not support SELECT queries and it won't.

**Comment by dgarijo** [comment]
Well, the custom queries are kind of select queries. Or are they all constructs?
