### ISSUE TITLE
Look at r4r

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#2]
https://github.com/cbadenes/r4r

In the Ontology Engineering Group, they re developing tools with a similar scope in mind. We should coordinate with @cbadenes to push this effort forward.

**Comment by sirspock** [comment]
I'm going to take the r4r idea but with JSON-LD inside velocity mapping

**Comment by dgarijo** [comment]
Cannot their approach be reused and extended? Or maybe having both mappings?

**Comment by dgarijo** [comment]
I am ok having JSON-LD frames in an earlier version, i just want to avoid reinventing the wheel

**Comment by sirspock** [comment]
We are using the JSON-LD in the actual API. So, we are not reinventing the wheel.

**Comment by dgarijo** [comment]
I see your point, but I think it's arguable. Let's not discuss here in any case.
