### ISSUE TITLE
Add documentation to concepts

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#27]
In the Ontology there is a definition (rdfs:comment) of what do the different concepts do.
It should also provide a link to the URI of the ontology, which provides extra documentation

**Comment by sirspock** [comment]
I don't understand the goal of this issue

**Comment by dgarijo** [comment]
In the swagger document, we should be able to see what the concepts mean:
![image](https://user-images.githubusercontent.com/1520666/75827830-56eefa80-5d5f-11ea-96eb-e0affd9a889a.png)

**Comment by dgarijo** [comment]
Fixed in https://github.com/KnowledgeCaptureAndDiscovery/OBA/pull/104
