### ISSUE TITLE
Evaluation DBPedia

### ISSUE THREAD

**Issue by sirspock** [KnowledgeCaptureAndDiscovery/OBA#45]

**Comment by dgarijo** [comment]
Any progress here?

**Comment by sirspock** [comment]
# Update

Dbpedia seems a real challenge.

## Generating the servers

The generating process is ok.
There two issues:
The DBpedia ontology has three weird properties.
You can see the modifications at https://youtu.be/WMILv3sfrzA

We dont have this problem on Wings or the Model Catalog

## Query the server

The framing process takes a lot time because the context.json has all the properties and classes of DBpedia. 
I can find a better approach but I must check the JSON/LD documentation.

This query takes more 10 seconds
```
curl -X GET "http://0.0.0.0:8080/v1.3.0/bands?page=1&per_page=3"
```
Get a simple resource takes 65 seconds (my computer)
```
curl -X GET "http://0.0.0.0:8080/v1.3.0/bands/Pink_Floyd" -H  "accept: application/json" -s -o /dev/null -w '%{time_starttransfer}\n' "$@"           х INT Py model-catalog
65.898489
```

### Missing information

The API response for Pink Floyd is: 
https://gist.github.com/8269fb91689a45cea5960669d4784779

As you can see, the information is not complete. Why?


On the see the dbpedia page http://dbpedia.org/page/Pink_Floyd, we can see the property: dbo:abstract. However, the api is not returning the property abstract.

If you review the OpenAPI Spec, OBA doesn't obtain the property. 
https://gist.github.com/sirspock/33f693523dead17a40416f4bb3700da3

Using Protege, I can't see any relationship

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2365990/80253715-9da9f400-862e-11ea-99e1-a62426f3ca7b.png">


<img width="914" alt="image" src="https://user-images.githubusercontent.com/2365990/80252674-8ff36f00-862c-11ea-88b0-cbefcb21a11f.png">

**Comment by dgarijo** [comment]
If it doesn't have a domain then it may be a property that applies to all paths, right? It's like rdfs:label...

**Comment by sirspock** [comment]
Done. You can test the v3.1.0
