### ISSUE TITLE
If a property has no domain, it doesn't get added in the responses

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#63]
See for example "Person":
https://api.models.mint.isi.edu/v1.4.0/persons/

Does not return the sd:name associated with the person. This happens because sd:name does not have a domain defined, only range. 

Currently OBA does the right thing: since it's not specified. OBA should detect these cases and let the user know with a warning. An option that could be provided is adding the property to all possible responses such as we do with rdfs:label.

**Comment by sirspock** [comment]
Duplicated.
