### ISSUE TITLE
Documentation: How to use /users/login 

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#66]
In the documentation, I haven't seen an example where we show how to authenticate  ~or create users~. We should show how to do this so they can handle post requests.

**Comment by dgarijo** [comment]
Since users won't be able to test authentication unless they have their own KG, I am removing high priority. I think we should still have an example about this.

**Comment by sirspock** [comment]
OBA doesn't support to create or delete users.

**Comment by dgarijo** [comment]
We need to show an example on how would authentication work, even if the user already exists.  Or point to the documentation in firebase where explains this.
