### ISSUE TITLE
DBPedia example does not work properly

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#70]
Paola attempted to use the configuration file for dbpedia and the program crashed on it, unfortunately.

**Comment by paoespinozarias** [comment]
I had been executing the last binary released but it doesn't work properly. 

Now, I  have followed the instructions of the second installation option (building binary) and both examples (full DBpedia and DBpedia_music) work fine.

**Comment by dgarijo** [comment]
@sirspock, maybe a new release will fix this issue.

**Comment by dgarijo** [comment]
Paola was able to generate the spec, so I will close the issue for now.

**Comment by paoespinozarias** [comment]
Right, the new binary released works. Thanks!
