### ISSUE TITLE
Separate frames (not contexts) for each class for framing.

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#85]
As we have seen, if the context file is not broken down it will be very slow for large ontologies.

We have agreed today that each class should have its frame. This way we don't need to generate a single giant frame to be loaded by all queries, which makes framing very slow when the ontologies are large.

Frames should only have 1 level depth (e.g., Model has versions and will be there, but their configs will be just URLs). We can have the level of depth adjustable with a parameter. Here is an example I have done with person knows person: https://tinyurl.com/y8y4769q. Note the difference with our discussion in https://tinyurl.com/y7rrcntw

Note: **Custom queries will require a custom frame.**

**Comment by sirspock** [comment]
We obtain the context from the response of SPARQL query.
The endpoint returns all the properties requires. Maybe, it using content negotiation I dont know.

The implementation code:
https://github.com/KnowledgeCaptureAndDiscovery/OBA_sparql/pull/11

**Comment by sirspock** [comment]
Note: Custom queries does not require a custom frame.
